services:
  - type: web
    name: site-analysis-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.address 0.0.0.0 --server.port $PORT --server.headless true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: VWORLD_API_KEY
        sync: false
      - key: VWORLD_DOMAIN
        sync: false
      - key: SGIS_CONSUMER_KEY
        sync: false
      - key: SGIS_CONSUMER_SECRET
        sync: false
      - key: KAKAO_REST_API_KEY
        sync: false
